export const data = [{
    cover: "./img/doom.jpg",
    title: "Doom Eternal",
    Developer: "id Software",
    Publisher: "Bethesda Softworks",
    release: "March 20, 2020",
    genre: ["First-person shooter"],
    platform: ["Microsoft Windows",
        "PlayStation 4",
        "Stadia",
        "Xbox One",
        "Nintendo Switch",
    ],
    alt: "Game_Doom",
    voted: "none",
}, {
    cover: "./img/resident-evil-2-biohazard-re2-deluxe-edition-cover.jpg",
    title: "Resident Evil 2",
    Developer: "Capcom R&D Division 1",
    Publisher: "Capcom",
    release: "January 25, 2019",
    genre: ["Survival Horror"],
    platform: ["Microsoft Windows",
        "PlayStation 4",
        "Xbox One",
    ],
    alt: "Resident_Evil_2",
    voted: "yes",
    star: 5,
}, {
    cover: "./img/spongebob-squarepants-battle-for-bikini-bottom-rehydrated-cover.jpg",
    title: `SpongeBob
SquarePants: Battle for Bikini Bottom - Rehydrated`,
    Developer: "Purple Lamp Studios",
    Publisher: "THQ Nordic",
    release: "June 23, 2020",
    genre: ["Platform", "Action - Adventure"],
    platform: ["Microsoft Windows",
        "Nintendo Switch",
        "PlayStation 4",
        "Xbox One",
    ],
    alt: "SpongeBob_SquarePants",
    voted: "none",
}, {
    cover: "./img/Cyberpunk 2077.jpg",
    title: "Cyberpunk 2077",
    Developer: "CD Projekt Red",
    Publisher: "CD Projekt",
    release: "NOVEMBER 19, 2020",
    genre: ["Role - Playing"],
    platform: ["Microsoft Windows",
        "PlayStation 4",
        "PlayStation 5",
        "Stadia",
        "Xbox One",
        "Xbox Series X",
    ],
    alt: "Cyberpunk_2077",
    voted: "none",
}, {
    cover: "./img/Insurgency-Sandstorm.jpg",
    title: `Insurgency:
Sandstorm`,
    Developer: "New World Interactive",
    Publisher: "Focus Home Interactive",
    release: "DECEMBER 12, 2018",
    genre: ["Tactical Shooter"],
    platform: ["Microsoft Windows",
        "PlayStation 4",
        "Xbox One",
    ],
    alt: "Insurgency_Sandstorm",
    voted: "none",
}, {
    cover: "./img/the-last-of-us-part-ii-cover.jpg",
    title: "The Last of Us Part2",
    Developer: "Naughty Dog",
    Publisher: "Sony Interactive Entertainment",
    release: "JUNE 19, 2020",
    genre: ["Action - Adventure", "Survival Horror"],
    platform: ["PlayStation 4"],
    alt: "The_Last_of_Us_Part2",
    voted: "yes",
    star: 4,
}, {
    cover: "./img/Wasteland_3.jpg",
    title: "Wasteland 3",
    Developer: "inXile Entertainment",
    Publisher: "Deep Silver",
    release: "AUGUST 28, 2020",
    genre: ["Role - Playing"],
    platform: ["Windows", "macOS", "Linux", "PlayStation 4", "Xbox One"],
    alt: "Wasteland3",
    voted: "none",
}, {
    cover: "./img/New World.jpg",
    title: "New World",
    Developer: "Amazon Game Studios Orange County",
    Publisher: "Amazon Game Studios",
    release: "AUGUST 25, 2020",
    genre: ["MMORPG"],
    platform: ["Microsoft Windows"],
    alt: "New_World",
    voted: "none",
}, {
    cover: "./img/Apex-legends-cover.jpg",
    title: "Apex Legends",
    Developer: "Respawn Entertainment",
    Publisher: "Electronic Arts",
    release: "February 4, 2019",
    genre: ["Battle Royale", "First - Person Shooter"],
    platform: ["Microsoft Windows",
        "PlayStation 4",
        "Xbox One",
        "Nintendo Switch",
    ],
    alt: "Apex-legends",
    voted: "yes",
    star: 4,
}, {
    cover: "./img/watch_dogs_legion.png",
    title: "Watch Dogs Legion",
    Developer: "Ubisoft Toronto",
    Publisher: "Ubisoft",
    release: "TBA, 2020",
    genre: ["Action - Adventure"],
    platform: ["Microsoft Windows",
        "PlayStation 4",
        "PlayStation 5",
        "Stadia",
        "Xbox One",
        "Xbox Series X",
    ],
    alt: "watch_dogs_legion",
}];